### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by delicacy1** [CodeKullen/QT#6]
_

**Comment by mikhoul** [comment]
In meantime I use this scripts and it is even more powerful at some points than QT: :blush:

https://greasyfork.org/en/scripts/9285-translate-google-tooltip

**Comment by delicacy1** [comment]
I should be able to see a transparent icon while selecting text, instead of selecting both alt plus text,
more over, it doesn't translate whole pages, so i do'nt see how more powerfull than qt it is..

**Comment by delicacy1** [comment]
Moved to S3.google.. fixed. adieu QT.

**Comment by C4R2T3N** [comment]
https://addons.mozilla.org/de/firefox/addon/quick-translator-origin/

**Comment by delicacy1** [comment]
unsubscribed.

**Comment by mikhoul** [comment]
@C4R2T3N  Link does not work: http://i.imgur.com/pBBVnkj.png

**Comment by johngraciliano** [comment]
I was happy to see this, but just for a brief time.  It seems to need a little more work.  Hopefully it will be ready in the near future.  ***Hopefully!***
